name: Deploy Shopify Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest

      - name: Authenticate and Deploy Theme
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_TOKEN }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
        run: shopify theme push --store $SHOPIFY_STORE_URL --theme $SHOPIFY_THEME_ID --force --allow-live